[package]
name = "values-collection"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cool-server"
path = "src/main.rs"

[dependencies]
clap = { version = "4.3.3", features = ["derive"] }
